name: my-test
on: [push]
jobs:
    my-test:
        runs-on: self-hosted
        #    runs-on: ubuntu-latest
        steps:
            #      - uses: actions/checkout@v2
            #      - uses: actions/setup-node@v1
            - run: msts
