apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.ghost_env}}
  name: ghost-{{.Values.release_ref}}
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:3-alpine
          ports:
            - containerPort: 2368
          env:
            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: database__connection__user
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: database__connection__password
            - name: database__client
              valueFrom:
                configMapKeyRef:
                  key: database__client
                  name: ghost-configmap-{{.Values.release_ref}}
            - name: database__connection__host
              valueFrom:
                configMapKeyRef:
                  key: database__connection__host
                  name: ghost-configmap-{{.Values.release_ref}}
            - name: database__connection__database
              valueFrom:
                configMapKeyRef:
                  key: database__connection__database
                  name: ghost-configmap-{{.Values.release_ref}}
            - name: url
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: ghost-configmap-{{.Values.release_ref}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.ghost_env}}
  name: ghost-service-{{.Values.release_ref}}
spec:
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
      protocol: TCP
      # 946efa00eb595d0359d1e4f257
      # 5fdf376a81a3050001eff20d:06a2f2978101233f5f57ae3976a1f914b3138e71c8128c4e154784de32a1b9fd