apiVersion: v1
kind: Secret
metadata:
  name: ghost-secret
  namespace: {{.Values.ghost_env}}
type: Opaque  # key value secret type
data:
  database__connection__user: dXNlcm5hbWU=
  database__connection__password: cGFzc3dvcmQ=

