apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Values.ghost_env}}
  name: ghost-configmap-{{.Values.release_ref}}
data:
  database__client: mysql
  database__connection__host: ghost-mysql-service-{{.Values.release_ref}}
  database__connection__database: ghost
  url: https://{{.Values.ingress_url}}