on: [push]
env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:
  deploy:
    runs-on: self-hosted
#    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: https://ghost-ingress3.airlan.cv.ua
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
