on: [push]

jobs:
  deploy:
    runs-on: self-hosted
#    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
      - run: npm config set strict-ssl false
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: https://ghost-ingress3.airlan.cv.ua
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
