name: deploying to prod
on:
    push:
        branches:
            - 'master'
        tags:
            - 'v.*'
env:
    DOMAIN: airlan.cv.ua
jobs:
    deploy-to-prod-env:
        runs-on: self-hosted
        environment:
            name: production
            url: https://prod-london.${{env.DOMAIN}}
        steps:
            - uses: actions/checkout@v2
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1.4.0
              with:
                  api-url: https://prod-london.${{env.DOMAIN}}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

