name: my-test
#on: [pull_request]
on:
    push:
        tags:
            - 'v.*'
env:
    DOMAIN: airlan.cv.ua
jobs:
    my-test:
        environment: ${{theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN}}
        runs-on: self-hosted
        steps:
#            - run: echo london-$GITHUB_HEAD_REF-${GITHUB_SHA::8}-pr$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-to-$GITHUB_BASE_REF
            - run: echo theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN
            - run: echo "TEST_ENVV=here-it-is" >> $GITHUB_ENV
