name: my-test
on: [pull_request]
jobs:
    my-test:
        runs-on: self-hosted
        steps:
            - run: echo $GITHUB_HEAD_REF-${GITHUB_SHA::8}-pr$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
