name: my-test
#on: [pull_request]
on:
    push:
        tags:
            - 'v.*'
env:
    DOMAIN: airlan.cv.ua
jobs:
    job_1:
        environment:
            name: teta3
            url: theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN
        runs-on: self-hosted
        outputs:
            output_1: ${{ steps.step_1.outputs.test }}
        steps:
            - id: step_1
              run: echo "::set-output name=test::theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN"


