name: my-env_url
#on: [pull_request]
on:
    push:
        tags:
            - 'v.*'
env:
    DOMAIN: airlan.cv.ua
jobs:
#    set_env:
#        environment:
#            name: teta3
#            url: ${{steps.env_info.outputs.env_url}}
#        runs-on: self-hosted
#        outputs:
#            url_output: ${{ steps.env_info.outputs.env_url }}
#        steps:
#            - id: env_info
#              run: echo "::set-output name=env_url::theme-${GITHUB_REF##*/}-london.$DOMAIN"
#
#    job_2:
#        environment:
#            name: teta4
#            url: ${{needs.set_env.outputs.url_output}}
#        runs-on: self-hosted
#        needs: set_env
#        steps:
#            - run: echo ${{toJson(github.ref)}}
#            - run: echo ${{needs.set_env.outputs.url_output}}

    job_3:
        runs-on: self-hosted
        environment:
            name: testing
            url: ${{env.RELEASE_REF}}
        steps:
            - run: echo "RELEASE_REF=theme-${GITHUB_REF##*/}-london.$DOMAIN" >> $GITHUB_ENV
            - run: echo $RELEASE_REF

    job_4:
        runs-on: self-hosted
        steps:
            - run: echo $RELEASE_REF
