name: my-env_url
#on: [pull_request]
on:
    push:
        tags:
            - 'v.*'
env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    DOMAIN: airlan.cv.ua
jobs:
#    set_env:
#        environment:
#            name: teta3
#            url: ${{steps.env_info.outputs.env_url}}
#        runs-on: self-hosted
#        outputs:
#            url_output: ${{ steps.env_info.outputs.env_url }}
#        steps:
#            - id: env_info
#              run: echo "::set-output name=env_url::theme-${GITHUB_REF##*/}-london.$DOMAIN"
#
#    job_2:
#        environment:
#            name: teta4
#            url: ${{needs.set_env.outputs.url_output}}
#        runs-on: self-hosted
#        needs: set_env
#        steps:
#            - run: echo ${{toJson(github.ref)}}
#            - run: echo ${{needs.set_env.outputs.url_output}}
    job_3:
        runs-on: self-hosted
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=theme-$RELEASE_V-london.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - run: microk8s.helm3 upgrade -i my-ghost-testing my-ghost --set release_ref=$RELEASE_V,ingress_url=$RELEASE_URL,ghost_env=testing

    job_4:
        runs-on: self-hosted
        needs: job_3
        environment:
            name: testing
            url: ${{ env.RELEASE_URL }}
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=testing-theme-$RELEASE_V-london.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1.4.0
              with:
                  api-url: https://${{ env.RELEASE_URL}}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

    job_5:
        runs-on: self-hosted
        needs: job_4
        environment:
            name: staging
            url: ${{ env.RELEASE_URL }}
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=staging-london.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1.4.0
              with:
                  api-url: https://${{ env.RELEASE_URL}}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

    job_6:
        runs-on: self-hosted
        needs: job_5
        environment:
            name: production
            url: ${{ env.RELEASE_URL }}
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=prod-london.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1.4.0
              with:
                  api-url: https://${{ env.RELEASE_URL}}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
