name: my-test
#on: [pull_request]
on:
    push:
        tags:
            - 'v.*'
env:
    DOMAIN: airlan.cv.ua
jobs:
    job_1:
        runs-on: self-hosted
        outputs:
            output_1: ${{ steps.step1.outputs.test }}
        steps:
            - id: step1
              run: echo "::set-output name=test::theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN"
#            - run: echo london-$GITHUB_HEAD_REF-${GITHUB_SHA::8}-pr$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-to-$GITHUB_BASE_REF
            - run: echo theme-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')-london.$DOMAIN
    job_2:
        needs: job_1
        steps:
            - run: echo ${{needs.job1.outputs.output_1}}

