name: Testing tag
on:
    push:
        branches:
            - '!master'
        tags:
            - 'v.*'
env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    DOMAIN: airlan.cv.ua
jobs:
    reset-k8s-test-env:
        runs-on: self-hosted
        environment:
            name: reset-k8s-test-env
            url: https://${{ env.RELEASE_URL }}
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=testing-theme-london-$RELEASE_V.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - run: microk8s.helm3 upgrade -i my-ghost-testing my-ghost --set release_ref=$RELEASE_V,ingress_url=$RELEASE_URL,ghost_env=testing

    deploy-to-test-env:
        runs-on: self-hosted
        needs: reset-k8s-test-env
        environment:
            name: testing
            url: https://${{ env.RELEASE_URL }}
        steps:
            - run: echo "TEMP_V=${GITHUB_REF##*/}" >> $GITHUB_ENV
            - run: echo "RELEASE_V=${TEMP_V//./-}" >> $GITHUB_ENV
            - run: echo "RELEASE_URL=testing-theme-london-$RELEASE_V.$DOMAIN" >> $GITHUB_ENV
            - uses: actions/checkout@v2
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1.4.0
              with:
                  api-url: https://${{ env.RELEASE_URL}}
                  api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

